apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: 'europe-north1-docker.pkg.dev/duolingo-halleb/react-app-repo/react-app:v1.0.0-8d353b2'
          ports:
            - containerPort: 8080
