apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80 # Port accessible depuis l'extérieur
      targetPort: 8080 # Port sur lequel NGINX écoute dans le container
  selector:
    app: react-frontend
